module load bedtools

bedtools intersect -u -header -a ../breaking_progeny_calls_into_groups/Fr1_resistant_samples.with_less_than_0.2_missing_data.fixed_sample_names.deconvoluted.vcf -b ../intersecting_megagam_calls_with_susceptible_calls/Fr1_susceptible_samples.with_less_than_0.2_missing_data.megagam_cands_5X_100X.MAF_MAX_0.00.fixed_sample_names.recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.meg_cands_MAF_in_susc_0.00.vcf 
bedtools intersect -u -header -a ../breaking_progeny_calls_into_groups/Fr1_resistant_samples.with_less_than_0.2_missing_data.fixed_sample_names.deconvoluted.vcf -b ../intersecting_megagam_calls_with_susceptible_calls/Fr1_susceptible_samples.with_less_than_0.2_missing_data.megagam_cands_5X_100X.MAF_MAX_0.01.fixed_sample_names.recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.meg_cands_MAF_in_susc_0.01.vcf 
bedtools intersect -u -header -a ../breaking_progeny_calls_into_groups/Fr1_resistant_samples.with_less_than_0.2_missing_data.fixed_sample_names.deconvoluted.vcf -b ../intersecting_megagam_calls_with_susceptible_calls/Fr1_susceptible_samples.with_less_than_0.2_missing_data.megagam_cands_5X_100X.MAF_MAX_0.05.fixed_sample_names.recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.meg_cands_MAF_in_susc_0.05.vcf 
bedtools intersect -u -header -a ../breaking_progeny_calls_into_groups/Fr1_resistant_samples.with_less_than_0.2_missing_data.fixed_sample_names.deconvoluted.vcf -b ../intersecting_megagam_calls_with_susceptible_calls/Fr1_susceptible_samples.with_less_than_0.2_missing_data.megagam_cands_5X_100X.MAF_MAX_0.10.fixed_sample_names.recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.meg_cands_MAF_in_susc_0.10.vcf 

module load vcftools
vcftools --recode --vcf Fr1_resistant_samples.with_less_than_0.2_missing_data.meg_cands_MAF_in_susc_0.00.vcf --maf 0.1 --out Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.00.MIN_MAF_in_rest_0.10
vcftools --recode --vcf Fr1_resistant_samples.with_less_than_0.2_missing_data.meg_cands_MAF_in_susc_0.01.vcf --maf 0.1 --out Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.01.MIN_MAF_in_rest_0.10
vcftools --recode --vcf Fr1_resistant_samples.with_less_than_0.2_missing_data.meg_cands_MAF_in_susc_0.05.vcf --maf 0.1 --out Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.05.MIN_MAF_in_rest_0.10
vcftools --recode --vcf Fr1_resistant_samples.with_less_than_0.2_missing_data.meg_cands_MAF_in_susc_0.10.vcf --maf 0.1 --out Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.10.MIN_MAF_in_rest_0.10

bedtools intersect -header -u -a ../breaking_progeny_calls_into_groups/Fr1_resistant_samples.with_less_than_0.2_missing_data.fixed_sample_names.deconvoluted.vcf -b Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.10.MIN_MAF_in_rest_0.10.recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.10.MIN_MAF_in_rest_0.10.no_recode.vcf
bedtools intersect -header -u -a ../breaking_progeny_calls_into_groups/Fr1_resistant_samples.with_less_than_0.2_missing_data.fixed_sample_names.deconvoluted.vcf -b Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.05.MIN_MAF_in_rest_0.10.recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.05.MIN_MAF_in_rest_0.10.no_recode.vcf
bedtools intersect -header -u -a ../breaking_progeny_calls_into_groups/Fr1_resistant_samples.with_less_than_0.2_missing_data.fixed_sample_names.deconvoluted.vcf -b Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.01.MIN_MAF_in_rest_0.10.recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.01.MIN_MAF_in_rest_0.10.no_recode.vcf
bedtools intersect -header -u -a ../breaking_progeny_calls_into_groups/Fr1_resistant_samples.with_less_than_0.2_missing_data.fixed_sample_names.deconvoluted.vcf -b Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.00.MIN_MAF_in_rest_0.10.recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.00.MIN_MAF_in_rest_0.10.no_recode.vcf

vcftools --vcf Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.00.MIN_MAF_in_rest_0.10.no_recode.vcf --counts2 --out Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.00.MIN_MAF_in_rest_0.10 
vcftools --vcf Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.01.MIN_MAF_in_rest_0.10.no_recode.vcf --counts2 --out Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.01.MIN_MAF_in_rest_0.10 
vcftools --vcf Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.05.MIN_MAF_in_rest_0.10.no_recode.vcf --counts2 --out Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.05.MIN_MAF_in_rest_0.10 
vcftools --vcf Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.10.MIN_MAF_in_rest_0.10.no_recode.vcf --counts2 --out Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.10.MIN_MAF_in_rest_0.10 

bedtools intersect -u -header -a ../breaking_progeny_calls_into_groups/Fr1_susceptible_samples.with_less_than_0.2_missing_data.fixed_sample_names.deconvoluted.vcf -b Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.00.MIN_MAF_in_rest_0.10.no_recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.00.MIN_MAF_in_rest_0.10._in_susceptible_.vcf
bedtools intersect -u -header -a ../breaking_progeny_calls_into_groups/Fr1_susceptible_samples.with_less_than_0.2_missing_data.fixed_sample_names.deconvoluted.vcf -b Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.01.MIN_MAF_in_rest_0.10.no_recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.01.MIN_MAF_in_rest_0.10._in_susceptible_.vcf
bedtools intersect -u -header -a ../breaking_progeny_calls_into_groups/Fr1_susceptible_samples.with_less_than_0.2_missing_data.fixed_sample_names.deconvoluted.vcf -b Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.05.MIN_MAF_in_rest_0.10.no_recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.05.MIN_MAF_in_rest_0.10._in_susceptible_.vcf
bedtools intersect -u -header -a ../breaking_progeny_calls_into_groups/Fr1_susceptible_samples.with_less_than_0.2_missing_data.fixed_sample_names.deconvoluted.vcf -b Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.10.MIN_MAF_in_rest_0.10.no_recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.10.MIN_MAF_in_rest_0.10._in_susceptible_.vcf


bedtools intersect -u -header -a ../../calls/freebayes/Fr1_megs.merged.freebayes.deconvoluted.vcf -b Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.00.MIN_MAF_in_rest_0.10.no_recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.00.MIN_MAF_in_rest_0.10._in_megs_.vcf
bedtools intersect -u -header -a ../../calls/freebayes/Fr1_megs.merged.freebayes.deconvoluted.vcf -b Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.01.MIN_MAF_in_rest_0.10.no_recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.01.MIN_MAF_in_rest_0.10._in_megs_.vcf
bedtools intersect -u -header -a ../../calls/freebayes/Fr1_megs.merged.freebayes.deconvoluted.vcf -b Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.05.MIN_MAF_in_rest_0.10.no_recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.05.MIN_MAF_in_rest_0.10._in_megs_.vcf
bedtools intersect -u -header -a ../../calls/freebayes/Fr1_megs.merged.freebayes.deconvoluted.vcf -b Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.10.MIN_MAF_in_rest_0.10.no_recode.vcf > Fr1_resistant_samples.with_less_than_0.2_missing_data.MAF_in_susc_0.10.MIN_MAF_in_rest_0.10._in_megs_.vcf


